global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'service-app-repository-payment'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - service-app-repository-payment:8000
          - host.docker.internal:8000

  - job_name: 'service-app-bff-payment'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - service-app-bff-payment:8100
          - host.docker.internal:8100

  - job_name: 'service-app-gateway'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - service-app-gateway:8765
          - host.docker.internal:8765

